[2016-12-14 09:17:09.753] [ERROR] error - { code: 500, message: '用户未登录' }
[2016-12-14 09:17:09.756] [ERROR] error - InternalServerError: 用户未登录
    at Object.throw (D:\workspace\JS\git\referral-server\node_modules\.2.0.0@koa\lib\context.js:91:23)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\LoginedChecker.js:34:26)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\responseWrapper.js:31:19
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\logger.js:7:15)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\redisSession.js:49:15
    at process._tickCallback (internal/process/next_tick.js:103:7)
[2016-12-14 09:23:26.022] [ERROR] error - { code: 500, message: '用户未登录' }
[2016-12-14 09:23:26.024] [ERROR] error - InternalServerError: 用户未登录
    at Object.throw (D:\workspace\JS\git\referral-server\node_modules\.2.0.0@koa\lib\context.js:91:23)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\LoginedChecker.js:34:26)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\responseWrapper.js:31:19
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\logger.js:7:15)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\redisSession.js:49:15
    at process._tickCallback (internal/process/next_tick.js:103:7)
[2016-12-14 09:38:43.019] [ERROR] error - { code: 500, message: 'split is not defined' }
[2016-12-14 09:38:43.021] [ERROR] error - ReferenceError: split is not defined
    at ReferralService.generateInSql (d:\workspace\JS\git\referral-server\service\BaseService.js:100:16)
    at ReferralService.findApplyTasks (d:\workspace\JS\git\referral-server\service\ReferralService.js:84:69)
    at GET/apply (d:\workspace\JS\git\referral-server\router\ReferralRouter.js:20:46)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at D:\workspace\JS\git\referral-server\node_modules\.7.0.1@koa-router\lib\router.js:321:16
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.7.0.1@koa-router\lib\router.js:326:31)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at allowedMethods (D:\workspace\JS\git\referral-server\node_modules\.7.0.1@koa-router\lib\router.js:361:12)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.7.0.1@koa-router\lib\router.js:315:32)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at allowedMethods (D:\workspace\JS\git\referral-server\node_modules\.7.0.1@koa-router\lib\router.js:361:12)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.7.0.1@koa-router\lib\router.js:315:32)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
[2016-12-14 09:39:06.777] [ERROR] error - { code: 500,
  message: 'ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'==1\' at line 3' }
[2016-12-14 09:39:06.779] [ERROR] error - { SequelizeBaseError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '==1' at line 3
    at Query.formatError (D:\workspace\JS\git\referral-server\node_modules\.3.27.0@sequelize\lib\dialects\mysql\query.js:175:14)
    at Query._callback (D:\workspace\JS\git\referral-server\node_modules\.3.27.0@sequelize\lib\dialects\mysql\query.js:49:21)
    at Query.Sequence.end (D:\workspace\JS\git\referral-server\node_modules\.2.12.0@mysql\lib\protocol\sequences\Sequence.js:86:24)
    at Query.ErrorPacket (D:\workspace\JS\git\referral-server\node_modules\.2.12.0@mysql\lib\protocol\sequences\Query.js:94:8)
    at Protocol._parsePacket (D:\workspace\JS\git\referral-server\node_modules\.2.12.0@mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (D:\workspace\JS\git\referral-server\node_modules\.2.12.0@mysql\lib\protocol\Parser.js:74:12)
    at Protocol.write (D:\workspace\JS\git\referral-server\node_modules\.2.12.0@mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\workspace\JS\git\referral-server\node_modules\.2.12.0@mysql\lib\Connection.js:109:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at TCP.onread [as _originalOnread] (net.js:551:20)
    at TCP.onread (D:\workspace\JS\git\referral-server\node_modules\.0.6.3@async-listener\glue.js:188:31)
  name: 'SequelizeDatabaseError',
  message: 'ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'==1\' at line 3',
  parent: 
   { Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '==1' at line 3
       at Query.Sequence._packetToError (D:\workspace\JS\git\referral-server\node_modules\.2.12.0@mysql\lib\protocol\sequences\Sequence.js:52:14)
       at Query.ErrorPacket (D:\workspace\JS\git\referral-server\node_modules\.2.12.0@mysql\lib\protocol\sequences\Query.js:83:18)
       at Protocol._parsePacket (D:\workspace\JS\git\referral-server\node_modules\.2.12.0@mysql\lib\protocol\Protocol.js:280:23)
       at Parser.write (D:\workspace\JS\git\referral-server\node_modules\.2.12.0@mysql\lib\protocol\Parser.js:74:12)
       at Protocol.write (D:\workspace\JS\git\referral-server\node_modules\.2.12.0@mysql\lib\protocol\Protocol.js:39:16)
       at Socket.<anonymous> (D:\workspace\JS\git\referral-server\node_modules\.2.12.0@mysql\lib\Connection.js:109:28)
       at emitOne (events.js:96:13)
       at Socket.emit (events.js:188:7)
       at readableAddChunk (_stream_readable.js:176:18)
       at TCP.onread [as _originalOnread] (net.js:551:20)
       at TCP.onread (D:\workspace\JS\git\referral-server\node_modules\.0.6.3@async-listener\glue.js:188:31)
       --------------------
       at Protocol._enqueue (D:\workspace\JS\git\referral-server\node_modules\.2.12.0@mysql\lib\protocol\Protocol.js:141:48)
       at Connection.query (D:\workspace\JS\git\referral-server\node_modules\.2.12.0@mysql\lib\Connection.js:214:25)
       at D:\workspace\JS\git\referral-server\node_modules\.3.27.0@sequelize\lib\dialects\mysql\query.js:40:21
       at Promise._execute (D:\workspace\JS\git\referral-server\node_modules\.3.4.6@bluebird\js\release\debuggability.js:299:9)
       at Promise._resolveFromExecutor (D:\workspace\JS\git\referral-server\node_modules\.3.4.6@bluebird\js\release\promise.js:481:18)
       at new Promise (D:\workspace\JS\git\referral-server\node_modules\.3.4.6@bluebird\js\release\promise.js:77:14)
       at Query.run (D:\workspace\JS\git\referral-server\node_modules\.3.27.0@sequelize\lib\dialects\mysql\query.js:39:17)
       at D:\workspace\JS\git\referral-server\node_modules\.3.27.0@sequelize\lib\sequelize.js:849:20
       at D:\workspace\JS\git\referral-server\node_modules\.2.2.0@retry-as-promised\index.js:40:21
       at Promise._execute (D:\workspace\JS\git\referral-server\node_modules\.3.4.6@bluebird\js\release\debuggability.js:299:9)
       at Promise._resolveFromExecutor (D:\workspace\JS\git\referral-server\node_modules\.3.4.6@bluebird\js\release\promise.js:481:18)
       at new Promise (D:\workspace\JS\git\referral-server\node_modules\.3.4.6@bluebird\js\release\promise.js:77:14)
       at retryAsPromised (D:\workspace\JS\git\referral-server\node_modules\.2.2.0@retry-as-promised\index.js:30:10)
       at ConnectionManager.<anonymous> (D:\workspace\JS\git\referral-server\node_modules\.3.2.0@continuation-local-storage\context.js:84:17)
       at ConnectionManager.tryCatcher (D:\workspace\JS\git\referral-server\node_modules\.3.4.6@bluebird\js\release\util.js:16:23)
       at Promise._settlePromiseFromHandler (D:\workspace\JS\git\referral-server\node_modules\.3.4.6@bluebird\js\release\promise.js:510:31)
     code: 'ER_PARSE_ERROR',
     errno: 1064,
     sqlState: '42000',
     index: 0,
     sql: 'SELECT COUNT(1) AS total \n                            FROM tb_patient tb_p JOIN tb_referral_form tb_rf ON tb_p.id_=tb_rf.patient_id_\n                            WHERE \n                            tb_rf.src_hospital_id_=\'7\'\n                             AND tb_p.status_==1' },
  original: 
   { Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '==1' at line 3
       at Query.Sequence._packetToError (D:\workspace\JS\git\referral-server\node_modules\.2.12.0@mysql\lib\protocol\sequences\Sequence.js:52:14)
       at Query.ErrorPacket (D:\workspace\JS\git\referral-server\node_modules\.2.12.0@mysql\lib\protocol\sequences\Query.js:83:18)
       at Protocol._parsePacket (D:\workspace\JS\git\referral-server\node_modules\.2.12.0@mysql\lib\protocol\Protocol.js:280:23)
       at Parser.write (D:\workspace\JS\git\referral-server\node_modules\.2.12.0@mysql\lib\protocol\Parser.js:74:12)
       at Protocol.write (D:\workspace\JS\git\referral-server\node_modules\.2.12.0@mysql\lib\protocol\Protocol.js:39:16)
       at Socket.<anonymous> (D:\workspace\JS\git\referral-server\node_modules\.2.12.0@mysql\lib\Connection.js:109:28)
       at emitOne (events.js:96:13)
       at Socket.emit (events.js:188:7)
       at readableAddChunk (_stream_readable.js:176:18)
       at TCP.onread [as _originalOnread] (net.js:551:20)
       at TCP.onread (D:\workspace\JS\git\referral-server\node_modules\.0.6.3@async-listener\glue.js:188:31)
       --------------------
       at Protocol._enqueue (D:\workspace\JS\git\referral-server\node_modules\.2.12.0@mysql\lib\protocol\Protocol.js:141:48)
       at Connection.query (D:\workspace\JS\git\referral-server\node_modules\.2.12.0@mysql\lib\Connection.js:214:25)
       at D:\workspace\JS\git\referral-server\node_modules\.3.27.0@sequelize\lib\dialects\mysql\query.js:40:21
       at Promise._execute (D:\workspace\JS\git\referral-server\node_modules\.3.4.6@bluebird\js\release\debuggability.js:299:9)
       at Promise._resolveFromExecutor (D:\workspace\JS\git\referral-server\node_modules\.3.4.6@bluebird\js\release\promise.js:481:18)
       at new Promise (D:\workspace\JS\git\referral-server\node_modules\.3.4.6@bluebird\js\release\promise.js:77:14)
       at Query.run (D:\workspace\JS\git\referral-server\node_modules\.3.27.0@sequelize\lib\dialects\mysql\query.js:39:17)
       at D:\workspace\JS\git\referral-server\node_modules\.3.27.0@sequelize\lib\sequelize.js:849:20
       at D:\workspace\JS\git\referral-server\node_modules\.2.2.0@retry-as-promised\index.js:40:21
       at Promise._execute (D:\workspace\JS\git\referral-server\node_modules\.3.4.6@bluebird\js\release\debuggability.js:299:9)
       at Promise._resolveFromExecutor (D:\workspace\JS\git\referral-server\node_modules\.3.4.6@bluebird\js\release\promise.js:481:18)
       at new Promise (D:\workspace\JS\git\referral-server\node_modules\.3.4.6@bluebird\js\release\promise.js:77:14)
       at retryAsPromised (D:\workspace\JS\git\referral-server\node_modules\.2.2.0@retry-as-promised\index.js:30:10)
       at ConnectionManager.<anonymous> (D:\workspace\JS\git\referral-server\node_modules\.3.2.0@continuation-local-storage\context.js:84:17)
       at ConnectionManager.tryCatcher (D:\workspace\JS\git\referral-server\node_modules\.3.4.6@bluebird\js\release\util.js:16:23)
       at Promise._settlePromiseFromHandler (D:\workspace\JS\git\referral-server\node_modules\.3.4.6@bluebird\js\release\promise.js:510:31)
     code: 'ER_PARSE_ERROR',
     errno: 1064,
     sqlState: '42000',
     index: 0,
     sql: 'SELECT COUNT(1) AS total \n                            FROM tb_patient tb_p JOIN tb_referral_form tb_rf ON tb_p.id_=tb_rf.patient_id_\n                            WHERE \n                            tb_rf.src_hospital_id_=\'7\'\n                             AND tb_p.status_==1' },
  sql: 'SELECT COUNT(1) AS total \n                            FROM tb_patient tb_p JOIN tb_referral_form tb_rf ON tb_p.id_=tb_rf.patient_id_\n                            WHERE \n                            tb_rf.src_hospital_id_=\'7\'\n                             AND tb_p.status_==1' }
[2016-12-14 09:42:06.680] [ERROR] error - { code: 500,
  message: 'ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'tb_p.id_card_number_ LIKE \'%333%\')\' at line 4' }
[2016-12-14 09:42:06.682] [ERROR] error - { SequelizeBaseError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'tb_p.id_card_number_ LIKE '%333%')' at line 4
    at Query.formatError (D:\workspace\JS\git\referral-server\node_modules\.3.27.0@sequelize\lib\dialects\mysql\query.js:175:14)
    at Query._callback (D:\workspace\JS\git\referral-server\node_modules\.3.27.0@sequelize\lib\dialects\mysql\query.js:49:21)
    at Query.Sequence.end (D:\workspace\JS\git\referral-server\node_modules\.2.12.0@mysql\lib\protocol\sequences\Sequence.js:86:24)
    at Query.ErrorPacket (D:\workspace\JS\git\referral-server\node_modules\.2.12.0@mysql\lib\protocol\sequences\Query.js:94:8)
    at Protocol._parsePacket (D:\workspace\JS\git\referral-server\node_modules\.2.12.0@mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (D:\workspace\JS\git\referral-server\node_modules\.2.12.0@mysql\lib\protocol\Parser.js:74:12)
    at Protocol.write (D:\workspace\JS\git\referral-server\node_modules\.2.12.0@mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\workspace\JS\git\referral-server\node_modules\.2.12.0@mysql\lib\Connection.js:109:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at TCP.onread [as _originalOnread] (net.js:551:20)
    at TCP.onread (D:\workspace\JS\git\referral-server\node_modules\.0.6.3@async-listener\glue.js:188:31)
  name: 'SequelizeDatabaseError',
  message: 'ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'tb_p.id_card_number_ LIKE \'%333%\')\' at line 4',
  parent: 
   { Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'tb_p.id_card_number_ LIKE '%333%')' at line 4
       at Query.Sequence._packetToError (D:\workspace\JS\git\referral-server\node_modules\.2.12.0@mysql\lib\protocol\sequences\Sequence.js:52:14)
       at Query.ErrorPacket (D:\workspace\JS\git\referral-server\node_modules\.2.12.0@mysql\lib\protocol\sequences\Query.js:83:18)
       at Protocol._parsePacket (D:\workspace\JS\git\referral-server\node_modules\.2.12.0@mysql\lib\protocol\Protocol.js:280:23)
       at Parser.write (D:\workspace\JS\git\referral-server\node_modules\.2.12.0@mysql\lib\protocol\Parser.js:74:12)
       at Protocol.write (D:\workspace\JS\git\referral-server\node_modules\.2.12.0@mysql\lib\protocol\Protocol.js:39:16)
       at Socket.<anonymous> (D:\workspace\JS\git\referral-server\node_modules\.2.12.0@mysql\lib\Connection.js:109:28)
       at emitOne (events.js:96:13)
       at Socket.emit (events.js:188:7)
       at readableAddChunk (_stream_readable.js:176:18)
       at TCP.onread [as _originalOnread] (net.js:551:20)
       at TCP.onread (D:\workspace\JS\git\referral-server\node_modules\.0.6.3@async-listener\glue.js:188:31)
       --------------------
       at Protocol._enqueue (D:\workspace\JS\git\referral-server\node_modules\.2.12.0@mysql\lib\protocol\Protocol.js:141:48)
       at Connection.query (D:\workspace\JS\git\referral-server\node_modules\.2.12.0@mysql\lib\Connection.js:214:25)
       at D:\workspace\JS\git\referral-server\node_modules\.3.27.0@sequelize\lib\dialects\mysql\query.js:40:21
       at Promise._execute (D:\workspace\JS\git\referral-server\node_modules\.3.4.6@bluebird\js\release\debuggability.js:299:9)
       at Promise._resolveFromExecutor (D:\workspace\JS\git\referral-server\node_modules\.3.4.6@bluebird\js\release\promise.js:481:18)
       at new Promise (D:\workspace\JS\git\referral-server\node_modules\.3.4.6@bluebird\js\release\promise.js:77:14)
       at Query.run (D:\workspace\JS\git\referral-server\node_modules\.3.27.0@sequelize\lib\dialects\mysql\query.js:39:17)
       at D:\workspace\JS\git\referral-server\node_modules\.3.27.0@sequelize\lib\sequelize.js:849:20
       at D:\workspace\JS\git\referral-server\node_modules\.2.2.0@retry-as-promised\index.js:40:21
       at Promise._execute (D:\workspace\JS\git\referral-server\node_modules\.3.4.6@bluebird\js\release\debuggability.js:299:9)
       at Promise._resolveFromExecutor (D:\workspace\JS\git\referral-server\node_modules\.3.4.6@bluebird\js\release\promise.js:481:18)
       at new Promise (D:\workspace\JS\git\referral-server\node_modules\.3.4.6@bluebird\js\release\promise.js:77:14)
       at retryAsPromised (D:\workspace\JS\git\referral-server\node_modules\.2.2.0@retry-as-promised\index.js:30:10)
       at D:\workspace\JS\git\referral-server\node_modules\.3.2.0@continuation-local-storage\context.js:84:17
       at tryCatcher (D:\workspace\JS\git\referral-server\node_modules\.3.4.6@bluebird\js\release\util.js:16:23)
       at Promise._settlePromiseFromHandler (D:\workspace\JS\git\referral-server\node_modules\.3.4.6@bluebird\js\release\promise.js:510:31)
     code: 'ER_PARSE_ERROR',
     errno: 1064,
     sqlState: '42000',
     index: 0,
     sql: 'SELECT COUNT(1) AS total \n                            FROM tb_patient tb_p JOIN tb_referral_task tb_rt ON tb_p.id_=tb_rt.patient_id_\n                            WHERE \n                            tb_rt.dest_hospital_id_=\'5\'\n                             AND tb_rt.status_=6 \n                             AND (tb_p.name_ LIKE \'%333%\' tb_p.id_card_number_ LIKE \'%333%\')' },
  original: 
   { Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'tb_p.id_card_number_ LIKE '%333%')' at line 4
       at Query.Sequence._packetToError (D:\workspace\JS\git\referral-server\node_modules\.2.12.0@mysql\lib\protocol\sequences\Sequence.js:52:14)
       at Query.ErrorPacket (D:\workspace\JS\git\referral-server\node_modules\.2.12.0@mysql\lib\protocol\sequences\Query.js:83:18)
       at Protocol._parsePacket (D:\workspace\JS\git\referral-server\node_modules\.2.12.0@mysql\lib\protocol\Protocol.js:280:23)
       at Parser.write (D:\workspace\JS\git\referral-server\node_modules\.2.12.0@mysql\lib\protocol\Parser.js:74:12)
       at Protocol.write (D:\workspace\JS\git\referral-server\node_modules\.2.12.0@mysql\lib\protocol\Protocol.js:39:16)
       at Socket.<anonymous> (D:\workspace\JS\git\referral-server\node_modules\.2.12.0@mysql\lib\Connection.js:109:28)
       at emitOne (events.js:96:13)
       at Socket.emit (events.js:188:7)
       at readableAddChunk (_stream_readable.js:176:18)
       at TCP.onread [as _originalOnread] (net.js:551:20)
       at TCP.onread (D:\workspace\JS\git\referral-server\node_modules\.0.6.3@async-listener\glue.js:188:31)
       --------------------
       at Protocol._enqueue (D:\workspace\JS\git\referral-server\node_modules\.2.12.0@mysql\lib\protocol\Protocol.js:141:48)
       at Connection.query (D:\workspace\JS\git\referral-server\node_modules\.2.12.0@mysql\lib\Connection.js:214:25)
       at D:\workspace\JS\git\referral-server\node_modules\.3.27.0@sequelize\lib\dialects\mysql\query.js:40:21
       at Promise._execute (D:\workspace\JS\git\referral-server\node_modules\.3.4.6@bluebird\js\release\debuggability.js:299:9)
       at Promise._resolveFromExecutor (D:\workspace\JS\git\referral-server\node_modules\.3.4.6@bluebird\js\release\promise.js:481:18)
       at new Promise (D:\workspace\JS\git\referral-server\node_modules\.3.4.6@bluebird\js\release\promise.js:77:14)
       at Query.run (D:\workspace\JS\git\referral-server\node_modules\.3.27.0@sequelize\lib\dialects\mysql\query.js:39:17)
       at D:\workspace\JS\git\referral-server\node_modules\.3.27.0@sequelize\lib\sequelize.js:849:20
       at D:\workspace\JS\git\referral-server\node_modules\.2.2.0@retry-as-promised\index.js:40:21
       at Promise._execute (D:\workspace\JS\git\referral-server\node_modules\.3.4.6@bluebird\js\release\debuggability.js:299:9)
       at Promise._resolveFromExecutor (D:\workspace\JS\git\referral-server\node_modules\.3.4.6@bluebird\js\release\promise.js:481:18)
       at new Promise (D:\workspace\JS\git\referral-server\node_modules\.3.4.6@bluebird\js\release\promise.js:77:14)
       at retryAsPromised (D:\workspace\JS\git\referral-server\node_modules\.2.2.0@retry-as-promised\index.js:30:10)
       at D:\workspace\JS\git\referral-server\node_modules\.3.2.0@continuation-local-storage\context.js:84:17
       at tryCatcher (D:\workspace\JS\git\referral-server\node_modules\.3.4.6@bluebird\js\release\util.js:16:23)
       at Promise._settlePromiseFromHandler (D:\workspace\JS\git\referral-server\node_modules\.3.4.6@bluebird\js\release\promise.js:510:31)
     code: 'ER_PARSE_ERROR',
     errno: 1064,
     sqlState: '42000',
     index: 0,
     sql: 'SELECT COUNT(1) AS total \n                            FROM tb_patient tb_p JOIN tb_referral_task tb_rt ON tb_p.id_=tb_rt.patient_id_\n                            WHERE \n                            tb_rt.dest_hospital_id_=\'5\'\n                             AND tb_rt.status_=6 \n                             AND (tb_p.name_ LIKE \'%333%\' tb_p.id_card_number_ LIKE \'%333%\')' },
  sql: 'SELECT COUNT(1) AS total \n                            FROM tb_patient tb_p JOIN tb_referral_task tb_rt ON tb_p.id_=tb_rt.patient_id_\n                            WHERE \n                            tb_rt.dest_hospital_id_=\'5\'\n                             AND tb_rt.status_=6 \n                             AND (tb_p.name_ LIKE \'%333%\' tb_p.id_card_number_ LIKE \'%333%\')' }
[2016-12-14 10:05:14.618] [ERROR] error - { code: 500, message: '用户未登录' }
[2016-12-14 10:05:14.620] [ERROR] error - InternalServerError: 用户未登录
    at Object.throw (D:\workspace\JS\git\referral-server\node_modules\.2.0.0@koa\lib\context.js:91:23)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\LoginedChecker.js:34:26)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\responseWrapper.js:31:19
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\logger.js:7:15)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\redisSession.js:49:15
    at process._tickCallback (internal/process/next_tick.js:103:7)
[2016-12-14 10:08:10.251] [ERROR] error - { code: 500, message: '此转诊申请已失效' }
[2016-12-14 10:08:10.253] [ERROR] error - Error: 此转诊申请已失效
    at consentTask.suggest.transaction (d:\workspace\JS\git\referral-server\service\ReferralService.js:266:23)
[2016-12-14 10:09:14.384] [ERROR] error - { code: 500, message: '此转诊申请已失效' }
[2016-12-14 10:09:14.386] [ERROR] error - Error: 此转诊申请已失效
    at consentTask.suggest.transaction (d:\workspace\JS\git\referral-server\service\ReferralService.js:267:23)
[2016-12-14 10:09:27.423] [ERROR] error - { code: 500, message: '此转诊申请已失效' }
[2016-12-14 10:09:27.424] [ERROR] error - Error: 此转诊申请已失效
    at consentTask.suggest.transaction (d:\workspace\JS\git\referral-server\service\ReferralService.js:267:23)
[2016-12-14 10:13:23.718] [ERROR] error - { code: 500, message: '此转诊申请已失效' }
[2016-12-14 10:13:23.721] [ERROR] error - Error: 此转诊申请已失效
    at consentTask.suggest.transaction (d:\workspace\JS\git\referral-server\service\ReferralService.js:274:23)
[2016-12-14 10:15:23.279] [ERROR] error - { code: 500, message: '此转诊申请已失效' }
[2016-12-14 10:15:23.280] [ERROR] error - Error: 此转诊申请已失效
    at transaction (d:\workspace\JS\git\referral-server\service\ReferralService.js:273:23)
[2016-12-14 10:18:43.769] [ERROR] error - { code: 500, message: '此转诊申请已失效' }
[2016-12-14 10:18:43.771] [ERROR] error - Error: 此转诊申请已失效
    at transaction (d:\workspace\JS\git\referral-server\service\ReferralService.js:273:23)
[2016-12-14 11:00:57.661] [ERROR] error - { code: 500, message: 'patient is not defined' }
[2016-12-14 11:00:57.663] [ERROR] error - ReferenceError: patient is not defined
    at transaction (d:\workspace\JS\git\referral-server\service\PatienService.js:104:14)
[2016-12-14 11:05:01.362] [ERROR] error - { code: 500, message: 'patient is not defined' }
[2016-12-14 11:05:01.364] [ERROR] error - ReferenceError: patient is not defined
    at transaction (d:\workspace\JS\git\referral-server\service\PatienService.js:104:14)
[2016-12-14 11:05:44.827] [ERROR] error - { code: 500, message: 'patient is not defined' }
[2016-12-14 11:05:44.829] [ERROR] error - ReferenceError: patient is not defined
    at delivery.patientId.transaction (d:\workspace\JS\git\referral-server\service\PatienService.js:114:14)
[2016-12-14 11:06:08.130] [ERROR] error - { code: 500, message: '患者档案不存在' }
[2016-12-14 11:06:08.133] [ERROR] error - Error: 患者档案不存在
    at delivery.patientId.transaction (d:\workspace\JS\git\referral-server\service\PatienService.js:116:23)
[2016-12-14 11:06:29.352] [ERROR] error - { code: 500, message: '患者档案不存在' }
[2016-12-14 11:06:29.353] [ERROR] error - Error: 患者档案不存在
    at transaction (d:\workspace\JS\git\referral-server\service\PatienService.js:114:23)
[2016-12-14 11:06:30.115] [ERROR] error - { code: 500, message: '患者档案不存在' }
[2016-12-14 11:06:30.115] [ERROR] error - Error: 患者档案不存在
    at transaction (d:\workspace\JS\git\referral-server\service\PatienService.js:114:23)
[2016-12-14 11:07:05.141] [ERROR] error - { code: 500, message: '患者档案不存在' }
[2016-12-14 11:07:05.141] [ERROR] error - Error: 患者档案不存在
    at transaction (d:\workspace\JS\git\referral-server\service\PatienService.js:117:23)
[2016-12-14 11:07:09.409] [ERROR] error - { code: 500, message: '患者档案不存在' }
[2016-12-14 11:07:09.410] [ERROR] error - Error: 患者档案不存在
    at transaction (d:\workspace\JS\git\referral-server\service\PatienService.js:117:23)
[2016-12-14 11:07:42.421] [ERROR] error - { code: 500, message: '患者档案不存在' }
[2016-12-14 11:07:42.423] [ERROR] error - Error: 患者档案不存在
    at transaction (d:\workspace\JS\git\referral-server\service\PatienService.js:117:23)
[2016-12-14 12:06:47.051] [ERROR] error - { code: 500, message: '用户未登录' }
[2016-12-14 12:06:47.055] [ERROR] error - InternalServerError: 用户未登录
    at Object.throw (D:\workspace\JS\git\referral-server\node_modules\.2.0.0@koa\lib\context.js:91:23)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\LoginedChecker.js:34:26)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\responseWrapper.js:31:19
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\logger.js:7:15)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\redisSession.js:49:15
    at process._tickCallback (internal/process/next_tick.js:103:7)
[2016-12-14 12:06:47.169] [ERROR] error - { code: 500, message: '用户未登录' }
[2016-12-14 12:06:47.169] [ERROR] error - InternalServerError: 用户未登录
    at Object.throw (D:\workspace\JS\git\referral-server\node_modules\.2.0.0@koa\lib\context.js:91:23)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\LoginedChecker.js:34:26)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\responseWrapper.js:31:19
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\logger.js:7:15)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\redisSession.js:49:15
    at process._tickCallback (internal/process/next_tick.js:103:7)
[2016-12-14 13:29:59.901] [ERROR] error - Cache key [DICTIONARY_ITEM_USE_ALL] is not exsit!
[2016-12-14 13:42:04.144] [ERROR] error - { code: 500, message: '用户未登录' }
[2016-12-14 13:42:04.145] [ERROR] error - InternalServerError: 用户未登录
    at Object.throw (D:\workspace\JS\git\referral-server\node_modules\.2.0.0@koa\lib\context.js:91:23)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\LoginedChecker.js:34:26)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\responseWrapper.js:31:19
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\logger.js:7:15)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\redisSession.js:49:15
    at process._tickCallback (internal/process/next_tick.js:103:7)
[2016-12-14 13:42:04.233] [ERROR] error - { code: 500, message: '用户未登录' }
[2016-12-14 13:42:04.233] [ERROR] error - InternalServerError: 用户未登录
    at Object.throw (D:\workspace\JS\git\referral-server\node_modules\.2.0.0@koa\lib\context.js:91:23)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\LoginedChecker.js:34:26)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\responseWrapper.js:31:19
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\logger.js:7:15)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\redisSession.js:49:15
    at process._tickCallback (internal/process/next_tick.js:103:7)
[2016-12-14 13:42:04.920] [ERROR] error - { code: 500, message: '用户未登录' }
[2016-12-14 13:42:04.920] [ERROR] error - InternalServerError: 用户未登录
    at Object.throw (D:\workspace\JS\git\referral-server\node_modules\.2.0.0@koa\lib\context.js:91:23)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\LoginedChecker.js:34:26)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\responseWrapper.js:31:19
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\logger.js:7:15)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\redisSession.js:49:15
    at process._tickCallback (internal/process/next_tick.js:103:7)
[2016-12-14 13:42:04.978] [ERROR] error - { code: 500, message: '用户未登录' }
[2016-12-14 13:42:04.978] [ERROR] error - InternalServerError: 用户未登录
    at Object.throw (D:\workspace\JS\git\referral-server\node_modules\.2.0.0@koa\lib\context.js:91:23)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\LoginedChecker.js:34:26)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\responseWrapper.js:31:19
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\logger.js:7:15)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\redisSession.js:49:15
    at process._tickCallback (internal/process/next_tick.js:103:7)
[2016-12-14 13:45:17.732] [ERROR] error - { code: 500, message: '用户未登录' }
[2016-12-14 13:45:17.732] [ERROR] error - InternalServerError: 用户未登录
    at Object.throw (D:\workspace\JS\git\referral-server\node_modules\.2.0.0@koa\lib\context.js:91:23)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\LoginedChecker.js:34:26)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\responseWrapper.js:31:19
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\logger.js:7:15)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\redisSession.js:49:15
    at process._tickCallback (internal/process/next_tick.js:103:7)
[2016-12-14 13:45:29.158] [ERROR] error - { code: 500, message: '用户未登录' }
[2016-12-14 13:45:29.158] [ERROR] error - InternalServerError: 用户未登录
    at Object.throw (D:\workspace\JS\git\referral-server\node_modules\.2.0.0@koa\lib\context.js:91:23)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\LoginedChecker.js:34:26)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\responseWrapper.js:31:19
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\logger.js:7:15)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\redisSession.js:49:15
    at process._tickCallback (internal/process/next_tick.js:103:7)
[2016-12-14 13:45:30.111] [ERROR] error - { code: 500, message: '用户未登录' }
[2016-12-14 13:45:30.111] [ERROR] error - InternalServerError: 用户未登录
    at Object.throw (D:\workspace\JS\git\referral-server\node_modules\.2.0.0@koa\lib\context.js:91:23)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\LoginedChecker.js:34:26)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\responseWrapper.js:31:19
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\logger.js:7:15)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\redisSession.js:49:15
    at process._tickCallback (internal/process/next_tick.js:103:7)
[2016-12-14 13:58:09.502] [ERROR] error - { code: 500, message: '用户未登录' }
[2016-12-14 13:58:09.505] [ERROR] error - InternalServerError: 用户未登录
    at Object.throw (D:\workspace\JS\git\referral-server\node_modules\.2.0.0@koa\lib\context.js:91:23)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\LoginedChecker.js:34:26)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\responseWrapper.js:31:19
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\logger.js:7:15)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\redisSession.js:49:15
    at process._tickCallback (internal/process/next_tick.js:103:7)
[2016-12-14 13:59:23.438] [ERROR] error - { code: 500, message: '用户未登录' }
[2016-12-14 13:59:23.440] [ERROR] error - InternalServerError: 用户未登录
    at Object.throw (D:\workspace\JS\git\referral-server\node_modules\.2.0.0@koa\lib\context.js:91:23)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\LoginedChecker.js:34:26)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\responseWrapper.js:31:19
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\logger.js:7:15)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\redisSession.js:49:15
    at process._tickCallback (internal/process/next_tick.js:103:7)
[2016-12-14 13:59:29.480] [ERROR] error - { code: 500, message: '用户未登录' }
[2016-12-14 13:59:29.481] [ERROR] error - InternalServerError: 用户未登录
    at Object.throw (D:\workspace\JS\git\referral-server\node_modules\.2.0.0@koa\lib\context.js:91:23)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\LoginedChecker.js:34:26)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\responseWrapper.js:31:19
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\logger.js:7:15)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\redisSession.js:49:15
    at process._tickCallback (internal/process/next_tick.js:103:7)
[2016-12-14 13:59:30.366] [ERROR] error - { code: 500, message: '用户未登录' }
[2016-12-14 13:59:30.366] [ERROR] error - InternalServerError: 用户未登录
    at Object.throw (D:\workspace\JS\git\referral-server\node_modules\.2.0.0@koa\lib\context.js:91:23)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\LoginedChecker.js:34:26)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\responseWrapper.js:31:19
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\logger.js:7:15)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\redisSession.js:49:15
    at process._tickCallback (internal/process/next_tick.js:103:7)
[2016-12-14 13:59:30.840] [ERROR] error - { code: 500, message: '用户未登录' }
[2016-12-14 13:59:30.841] [ERROR] error - InternalServerError: 用户未登录
    at Object.throw (D:\workspace\JS\git\referral-server\node_modules\.2.0.0@koa\lib\context.js:91:23)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\LoginedChecker.js:34:26)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\responseWrapper.js:31:19
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\logger.js:7:15)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\redisSession.js:49:15
    at process._tickCallback (internal/process/next_tick.js:103:7)
[2016-12-14 14:06:33.338] [ERROR] error - { code: 500, message: '用户未登录' }
[2016-12-14 14:06:33.340] [ERROR] error - InternalServerError: 用户未登录
    at Object.throw (D:\workspace\JS\git\referral-server\node_modules\.2.0.0@koa\lib\context.js:91:23)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\LoginedChecker.js:34:26)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\responseWrapper.js:31:19
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\logger.js:7:15)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\redisSession.js:49:15
    at process._tickCallback (internal/process/next_tick.js:103:7)
[2016-12-14 14:06:45.675] [ERROR] error - { code: 500, message: '用户未登录' }
[2016-12-14 14:06:45.676] [ERROR] error - InternalServerError: 用户未登录
    at Object.throw (D:\workspace\JS\git\referral-server\node_modules\.2.0.0@koa\lib\context.js:91:23)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\LoginedChecker.js:34:26)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\responseWrapper.js:31:19
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\logger.js:7:15)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\redisSession.js:49:15
    at process._tickCallback (internal/process/next_tick.js:103:7)
[2016-12-14 14:07:32.677] [ERROR] error - { code: 500, message: '用户未登录' }
[2016-12-14 14:07:32.677] [ERROR] error - InternalServerError: 用户未登录
    at Object.throw (D:\workspace\JS\git\referral-server\node_modules\.2.0.0@koa\lib\context.js:91:23)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\LoginedChecker.js:34:26)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\responseWrapper.js:31:19
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\logger.js:7:15)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\redisSession.js:49:15
    at process._tickCallback (internal/process/next_tick.js:103:7)
[2016-12-14 14:07:32.742] [ERROR] error - { code: 500, message: '用户未登录' }
[2016-12-14 14:07:32.742] [ERROR] error - InternalServerError: 用户未登录
    at Object.throw (D:\workspace\JS\git\referral-server\node_modules\.2.0.0@koa\lib\context.js:91:23)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\LoginedChecker.js:34:26)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\responseWrapper.js:31:19
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\logger.js:7:15)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\redisSession.js:49:15
    at process._tickCallback (internal/process/next_tick.js:103:7)
[2016-12-14 14:09:14.806] [ERROR] error - { code: 500, message: '用户未登录' }
[2016-12-14 14:09:14.806] [ERROR] error - InternalServerError: 用户未登录
    at Object.throw (D:\workspace\JS\git\referral-server\node_modules\.2.0.0@koa\lib\context.js:91:23)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\LoginedChecker.js:34:26)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\responseWrapper.js:31:19
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\logger.js:7:15)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\redisSession.js:49:15
    at process._tickCallback (internal/process/next_tick.js:103:7)
[2016-12-14 14:09:16.090] [ERROR] error - { code: 500, message: '用户未登录' }
[2016-12-14 14:09:16.091] [ERROR] error - InternalServerError: 用户未登录
    at Object.throw (D:\workspace\JS\git\referral-server\node_modules\.2.0.0@koa\lib\context.js:91:23)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\LoginedChecker.js:34:26)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\responseWrapper.js:31:19
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\logger.js:7:15)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\redisSession.js:49:15
    at process._tickCallback (internal/process/next_tick.js:103:7)
[2016-12-14 14:10:45.498] [ERROR] error - { code: 500, message: '用户未登录' }
[2016-12-14 14:10:45.499] [ERROR] error - InternalServerError: 用户未登录
    at Object.throw (D:\workspace\JS\git\referral-server\node_modules\.2.0.0@koa\lib\context.js:91:23)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\LoginedChecker.js:34:26)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\responseWrapper.js:31:19
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\logger.js:7:15)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\redisSession.js:49:15
    at process._tickCallback (internal/process/next_tick.js:103:7)
[2016-12-14 14:10:47.305] [ERROR] error - { code: 500, message: '用户未登录' }
[2016-12-14 14:10:47.305] [ERROR] error - InternalServerError: 用户未登录
    at Object.throw (D:\workspace\JS\git\referral-server\node_modules\.2.0.0@koa\lib\context.js:91:23)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\LoginedChecker.js:34:26)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\responseWrapper.js:31:19
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\logger.js:7:15)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\redisSession.js:49:15
    at process._tickCallback (internal/process/next_tick.js:103:7)
[2016-12-14 14:10:52.976] [ERROR] error - { code: 500, message: '用户未登录' }
[2016-12-14 14:10:52.977] [ERROR] error - InternalServerError: 用户未登录
    at Object.throw (D:\workspace\JS\git\referral-server\node_modules\.2.0.0@koa\lib\context.js:91:23)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\LoginedChecker.js:34:26)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\responseWrapper.js:31:19
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\logger.js:7:15)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\redisSession.js:49:15
    at process._tickCallback (internal/process/next_tick.js:103:7)
[2016-12-14 14:11:02.572] [ERROR] error - { code: 500, message: '用户未登录' }
[2016-12-14 14:11:02.572] [ERROR] error - InternalServerError: 用户未登录
    at Object.throw (D:\workspace\JS\git\referral-server\node_modules\.2.0.0@koa\lib\context.js:91:23)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\LoginedChecker.js:34:26)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\responseWrapper.js:31:19
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\logger.js:7:15)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\redisSession.js:49:15
    at process._tickCallback (internal/process/next_tick.js:103:7)
[2016-12-14 14:11:18.679] [ERROR] error - { code: 500, message: '用户未登录' }
[2016-12-14 14:11:18.680] [ERROR] error - InternalServerError: 用户未登录
    at Object.throw (D:\workspace\JS\git\referral-server\node_modules\.2.0.0@koa\lib\context.js:91:23)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\LoginedChecker.js:34:26)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\responseWrapper.js:31:19
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\logger.js:7:15)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\redisSession.js:49:15
    at process._tickCallback (internal/process/next_tick.js:103:7)
[2016-12-14 14:11:19.657] [ERROR] error - { code: 500, message: '用户未登录' }
[2016-12-14 14:11:19.657] [ERROR] error - InternalServerError: 用户未登录
    at Object.throw (D:\workspace\JS\git\referral-server\node_modules\.2.0.0@koa\lib\context.js:91:23)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\LoginedChecker.js:34:26)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\responseWrapper.js:31:19
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\logger.js:7:15)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\redisSession.js:49:15
    at process._tickCallback (internal/process/next_tick.js:103:7)
[2016-12-14 14:11:23.748] [ERROR] error - { code: 500, message: '用户名密码错误' }
[2016-12-14 14:11:23.749] [ERROR] error - InternalServerError: 用户名密码错误
    at Object.throw (D:\workspace\JS\git\referral-server\node_modules\.2.0.0@koa\lib\context.js:91:23)
    at middleware (d:\workspace\JS\git\referral-server\router\ManagerSignRouter.js:27:30)
[2016-12-14 14:11:44.832] [ERROR] error - { code: 500, message: '用户未登录' }
[2016-12-14 14:11:44.832] [ERROR] error - InternalServerError: 用户未登录
    at Object.throw (D:\workspace\JS\git\referral-server\node_modules\.2.0.0@koa\lib\context.js:91:23)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\LoginedChecker.js:34:26)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\responseWrapper.js:31:19
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\logger.js:7:15)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\redisSession.js:49:15
    at process._tickCallback (internal/process/next_tick.js:103:7)
[2016-12-14 14:11:45.768] [ERROR] error - { code: 500, message: '用户未登录' }
[2016-12-14 14:11:45.769] [ERROR] error - InternalServerError: 用户未登录
    at Object.throw (D:\workspace\JS\git\referral-server\node_modules\.2.0.0@koa\lib\context.js:91:23)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\LoginedChecker.js:34:26)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\responseWrapper.js:31:19
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\logger.js:7:15)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\redisSession.js:49:15
    at process._tickCallback (internal/process/next_tick.js:103:7)
[2016-12-14 14:13:59.490] [ERROR] error - { code: 500, message: '用户未登录' }
[2016-12-14 14:13:59.490] [ERROR] error - InternalServerError: 用户未登录
    at Object.throw (D:\workspace\JS\git\referral-server\node_modules\.2.0.0@koa\lib\context.js:91:23)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\LoginedChecker.js:34:26)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\responseWrapper.js:31:19
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\logger.js:7:15)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\redisSession.js:49:15
    at process._tickCallback (internal/process/next_tick.js:103:7)
[2016-12-14 14:14:00.546] [ERROR] error - { code: 500, message: '用户未登录' }
[2016-12-14 14:14:00.547] [ERROR] error - InternalServerError: 用户未登录
    at Object.throw (D:\workspace\JS\git\referral-server\node_modules\.2.0.0@koa\lib\context.js:91:23)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\LoginedChecker.js:34:26)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\responseWrapper.js:31:19
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\logger.js:7:15)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\redisSession.js:49:15
    at process._tickCallback (internal/process/next_tick.js:103:7)
[2016-12-14 14:14:41.778] [ERROR] error - { code: 500, message: '用户未登录' }
[2016-12-14 14:14:41.778] [ERROR] error - InternalServerError: 用户未登录
    at Object.throw (D:\workspace\JS\git\referral-server\node_modules\.2.0.0@koa\lib\context.js:91:23)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\LoginedChecker.js:34:26)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\responseWrapper.js:31:19
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\logger.js:7:15)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\redisSession.js:49:15
    at process._tickCallback (internal/process/next_tick.js:103:7)
[2016-12-14 14:14:42.552] [ERROR] error - { code: 500, message: '用户未登录' }
[2016-12-14 14:14:42.552] [ERROR] error - InternalServerError: 用户未登录
    at Object.throw (D:\workspace\JS\git\referral-server\node_modules\.2.0.0@koa\lib\context.js:91:23)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\LoginedChecker.js:34:26)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\responseWrapper.js:31:19
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\logger.js:7:15)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\redisSession.js:49:15
    at process._tickCallback (internal/process/next_tick.js:103:7)
[2016-12-14 14:15:08.694] [ERROR] error - { code: 500, message: '用户未登录' }
[2016-12-14 14:15:08.694] [ERROR] error - InternalServerError: 用户未登录
    at Object.throw (D:\workspace\JS\git\referral-server\node_modules\.2.0.0@koa\lib\context.js:91:23)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\LoginedChecker.js:34:26)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\responseWrapper.js:31:19
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\logger.js:7:15)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\redisSession.js:49:15
    at process._tickCallback (internal/process/next_tick.js:103:7)
[2016-12-14 14:15:08.748] [ERROR] error - { code: 500, message: '用户未登录' }
[2016-12-14 14:15:08.749] [ERROR] error - InternalServerError: 用户未登录
    at Object.throw (D:\workspace\JS\git\referral-server\node_modules\.2.0.0@koa\lib\context.js:91:23)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\LoginedChecker.js:34:26)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\responseWrapper.js:31:19
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\logger.js:7:15)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\redisSession.js:49:15
    at process._tickCallback (internal/process/next_tick.js:103:7)
[2016-12-14 16:12:34.833] [ERROR] error - { code: 500, message: '用户未登录' }
[2016-12-14 16:12:34.835] [ERROR] error - InternalServerError: 用户未登录
    at Object.throw (D:\workspace\JS\git\referral-server\node_modules\.2.0.0@koa\lib\context.js:91:23)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\LoginedChecker.js:34:26)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\responseWrapper.js:31:19
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at app.use (d:\workspace\JS\git\referral-server\middlewares\logger.js:7:15)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at d:\workspace\JS\git\referral-server\middlewares\redisSession.js:49:15
    at process._tickCallback (internal/process/next_tick.js:103:7)
[2016-12-14 16:13:07.132] [ERROR] error - { code: 500,
  message: 'Cannot read property \'hospital\' of undefined' }
[2016-12-14 16:13:07.133] [ERROR] error - TypeError: Cannot read property 'hospital' of undefined
    at GET/last/:patientId (d:\workspace\JS\git\referral-server\router\ExamineRouter.js:38:81)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at D:\workspace\JS\git\referral-server\node_modules\.7.0.1@koa-router\lib\router.js:321:16
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.7.0.1@koa-router\lib\router.js:326:31)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at allowedMethods (D:\workspace\JS\git\referral-server\node_modules\.7.0.1@koa-router\lib\router.js:361:12)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.7.0.1@koa-router\lib\router.js:315:32)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at allowedMethods (D:\workspace\JS\git\referral-server\node_modules\.7.0.1@koa-router\lib\router.js:361:12)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.7.0.1@koa-router\lib\router.js:315:32)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at allowedMethods (D:\workspace\JS\git\referral-server\node_modules\.7.0.1@koa-router\lib\router.js:361:12)
    at dispatch (D:\workspace\JS\git\referral-server\node_modules\.3.2.1@koa-compose\index.js:44:32)
